# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_rasa_topping.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateStok(object):
    def setupUi(self, UpdateStok):
        UpdateStok.setObjectName("UpdateStok")
        UpdateStok.resize(440, 196)
        self.verticalLayoutWidget = QtWidgets.QWidget(UpdateStok)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelJudul = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul.setFont(font)
        self.labelJudul.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJudul.setObjectName("labelJudul")
        self.verticalLayout.addWidget(self.labelJudul)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.comboBoxJenis = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxJenis.setObjectName("comboBoxJenis")
        self.comboBoxJenis.addItem("")
        self.comboBoxJenis.addItem("")
        self.verticalLayout.addWidget(self.comboBoxJenis)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)
        self.pushButtonGanti = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonGanti.setObjectName("pushButtonGanti")
        self.gridLayout.addWidget(self.pushButtonGanti, 1, 2, 1, 1)
        self.lineEditInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditInput.setObjectName("lineEditInput")
        self.gridLayout.addWidget(self.lineEditInput, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.labelWarning = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelWarning.setObjectName("labelWarning")
        self.verticalLayout.addWidget(self.labelWarning)

        self.retranslateUi(UpdateStok)
        QtCore.QMetaObject.connectSlotsByName(UpdateStok)

    def retranslateUi(self, UpdateStok):
        _translate = QtCore.QCoreApplication.translate
        UpdateStok.setWindowTitle(_translate("UpdateStok", "Form"))
        self.labelJudul.setText(_translate("UpdateStok", "Edit Menu"))
        self.comboBoxJenis.setItemText(0, _translate("UpdateStok", "Flavour"))
        self.comboBoxJenis.setItemText(1, _translate("UpdateStok", "Topping"))
        self.pushButtonGanti.setText(_translate("UpdateStok", "Ganti"))
        self.labelWarning.setText(_translate("UpdateStok", "Klik tombol ganti untuk mengganti nama..!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UpdateStok = QtWidgets.QWidget()
    ui = Ui_UpdateStok()
    ui.setupUi(UpdateStok)
    UpdateStok.show()
    sys.exit(app.exec_())
