# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_rasa_topping.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 321)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelJudul = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul.setFont(font)
        self.labelJudul.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJudul.setObjectName("labelJudul")
        self.verticalLayout.addWidget(self.labelJudul)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.comboBoxJenis = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxJenis.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxJenis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxJenis.setObjectName("comboBoxJenis")
        self.comboBoxJenis.addItem("")
        self.comboBoxJenis.addItem("")
        self.verticalLayout.addWidget(self.comboBoxJenis)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lineEditInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditInput.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditInput.setObjectName("lineEditInput")
        self.verticalLayout.addWidget(self.lineEditInput)
        self.pushButtonGanti = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonGanti.setObjectName("pushButtonGanti")
        self.verticalLayout.addWidget(self.pushButtonGanti)
        self.labelWarning = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelWarning.setObjectName("labelWarning")
        self.verticalLayout.addWidget(self.labelWarning)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelJudul.setText(_translate("MainWindow", "Edit Menu"))
        self.comboBoxJenis.setItemText(0, _translate("MainWindow", "Flavour"))
        self.comboBoxJenis.setItemText(1, _translate("MainWindow", "Topping"))
        self.pushButtonGanti.setText(_translate("MainWindow", "Ganti"))
        self.labelWarning.setText(_translate("MainWindow", "Klik tombol ganti untuk mengganti nama..!!!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
