# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(768, 461)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1010, 544))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonBackHistory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonBackHistory.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBackHistory.setFont(font)
        self.pushButtonBackHistory.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonBackHistory.setObjectName("pushButtonBackHistory")
        self.horizontalLayout.addWidget(self.pushButtonBackHistory)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetHistory = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidgetHistory.setMinimumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidgetHistory.setFont(font)
        self.tableWidgetHistory.setDragEnabled(False)
        self.tableWidgetHistory.setColumnCount(6)
        self.tableWidgetHistory.setObjectName("tableWidgetHistory")
        self.tableWidgetHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetHistory.setHorizontalHeaderItem(5, item)
        self.tableWidgetHistory.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidgetHistory)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonBackHistory.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "History Penjualan"))
        item = self.tableWidgetHistory.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nama Pembeli"))
        item = self.tableWidgetHistory.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Instagram"))
        item = self.tableWidgetHistory.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Tanggal Pembelian"))
        item = self.tableWidgetHistory.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Varian Rasa"))
        item = self.tableWidgetHistory.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Ukuran Cup"))
        item = self.tableWidgetHistory.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Jumlah Pembelian"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
