# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pembayaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pembayaran(object):
    def setupUi(self, pembayaran):
        pembayaran.setObjectName("pembayaran")
        pembayaran.resize(492, 381)
        self.centralwidget = QtWidgets.QWidget(pembayaran)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.qr_frame = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qr_frame.sizePolicy().hasHeightForWidth())
        self.qr_frame.setSizePolicy(sizePolicy)
        self.qr_frame.setMinimumSize(QtCore.QSize(250, 250))
        self.qr_frame.setMaximumSize(QtCore.QSize(250, 250))
        self.qr_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.qr_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.qr_frame.setObjectName("qr_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.qr_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.qr_label = QtWidgets.QLabel(self.qr_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qr_label.sizePolicy().hasHeightForWidth())
        self.qr_label.setSizePolicy(sizePolicy)
        self.qr_label.setText("")
        self.qr_label.setPixmap(QtGui.QPixmap("../../../Pictures/rumahsakit/Indra.png"))
        self.qr_label.setObjectName("qr_label")
        self.horizontalLayout_6.addWidget(self.qr_label)
        self.horizontalLayout_5.addWidget(self.qr_frame)
        self.verticalLayout.addWidget(self.frame)
        self.voucer_frame = QtWidgets.QFrame(self.centralwidget)
        self.voucer_frame.setMinimumSize(QtCore.QSize(0, 100))
        self.voucer_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.voucer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voucer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voucer_frame.setObjectName("voucer_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.voucer_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.voucer_content = QtWidgets.QFrame(self.voucer_frame)
        self.voucer_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.voucer_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voucer_content.setObjectName("voucer_content")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.voucer_content)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.voucer_label = QtWidgets.QLabel(self.voucer_content)
        self.voucer_label.setObjectName("voucer_label")
        self.horizontalLayout_7.addWidget(self.voucer_label)
        self.voucer_input = QtWidgets.QLineEdit(self.voucer_content)
        self.voucer_input.setText("")
        self.voucer_input.setObjectName("voucer_input")
        self.horizontalLayout_7.addWidget(self.voucer_input)
        self.apply_button = QtWidgets.QPushButton(self.voucer_content)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_7.addWidget(self.apply_button)
        self.verticalLayout_3.addWidget(self.voucer_content)
        self.voucer_info = QtWidgets.QLabel(self.voucer_frame)
        self.voucer_info.setText("")
        self.voucer_info.setAlignment(QtCore.Qt.AlignCenter)
        self.voucer_info.setObjectName("voucer_info")
        self.verticalLayout_3.addWidget(self.voucer_info)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_Selesai = QtWidgets.QPushButton(self.voucer_frame)
        self.pushButton_Selesai.setObjectName("pushButton_Selesai")
        self.horizontalLayout.addWidget(self.pushButton_Selesai)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.voucer_frame)
        pembayaran.setCentralWidget(self.centralwidget)

        self.retranslateUi(pembayaran)
        QtCore.QMetaObject.connectSlotsByName(pembayaran)

    def retranslateUi(self, pembayaran):
        _translate = QtCore.QCoreApplication.translate
        pembayaran.setWindowTitle(_translate("pembayaran", "MainWindow"))
        self.voucer_label.setText(_translate("pembayaran", "Voucer : "))
        self.apply_button.setText(_translate("pembayaran", "Apply"))
        self.pushButton_Selesai.setText(_translate("pembayaran", "Selesai"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pembayaran = QtWidgets.QMainWindow()
    ui = Ui_pembayaran()
    ui.setupUi(pembayaran)
    pembayaran.show()
    sys.exit(app.exec_())
