# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tampilan_awal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 358)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 387, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.admin_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.admin_button.setStyleSheet("")
        self.admin_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admin_button.setIcon(icon)
        self.admin_button.setObjectName("admin_button")
        self.horizontalLayout.addWidget(self.admin_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelNamaAlat = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelNamaAlat.setFont(font)
        self.labelNamaAlat.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNamaAlat.setObjectName("labelNamaAlat")
        self.verticalLayout.addWidget(self.labelNamaAlat)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.labelDeskripsiAlat = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDeskripsiAlat.setFont(font)
        self.labelDeskripsiAlat.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDeskripsiAlat.setObjectName("labelDeskripsiAlat")
        self.verticalLayout.addWidget(self.labelDeskripsiAlat)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 5, 5, 5)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditNama = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditNama.setObjectName("lineEditNama")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditNama)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButtonPesan = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonPesan.setObjectName("pushButtonPesan")
        self.verticalLayout.addWidget(self.pushButtonPesan)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "v1.0"))
        self.labelNamaAlat.setText(_translate("Form", "Ice Cream Vending Machine"))
        self.labelDeskripsiAlat.setText(_translate("Form", "Silahkan nama Anda!"))
        self.label.setText(_translate("Form", "Masukkan Nama : "))
        self.pushButtonPesan.setText(_translate("Form", "Pesan"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
